version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=property_management_db
    ports:
      - 5432:5432
    # volumes:
    #   - ./data:/var/lib/postgresql/data
